name: Tox 🧪

on:
  push:
    branches: [ main, develop ]

jobs:
  tox_py311:
    runs-on: ubuntu-latest
    container:
      image: python:3.11-slim

    steps:
      - name: Git setup
        run: |
          apt-get update && apt-get install -y coreutils git

      - name: Checkout code  📦
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Run tests with tox 🧪
        run: |
          pip install tox==4.30.3
          tox -e py311

  tox_py312:
    runs-on: ubuntu-latest
    container:
      image: python:3.12-slim

    steps:
      - name: Git setup
        run: |
          apt-get update && apt-get install -y coreutils git

      - name: Checkout code  📦
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Run tests with tox 🧪
        run: |
          pip install tox==4.30.3
          tox -e py312

  tox_py313:
    runs-on: ubuntu-latest
    container:
      image: python:3.13-slim

    steps:
      - name: Git and compiler setup
        run: |
          apt-get update && apt-get install -y coreutils git gcc g++

      - name: Checkout code  📦
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Run tests with tox 🧪
        run: |
          pip install tox==4.30.3
          tox -e py313
